import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// The Remix server build is generated by `npm run build`.
import * as build from "../build/server";

export const onRequest = createPagesFunctionHandler({
  build,
});
